config/routes.rb
Rails.application.routes.draw do
  # get "number" => "contact#number"
  # get "address" => "contact#address"
  # get 'play/call'

  root "employees#index"
  resources :employees
  post "create" => "employees#create"
  get "new" => "employees#new"


  get "maxx" => "maxx#new"
  post "maxx" => "maxx#create"
  get "display" => "maxx#show"
  get "detail" => "maxx#connect"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
	validates :name, :contact, presence: true
	validates :address, presence: true
end

app/models/webb.rb
class Webb < ApplicationRecord
	validates :email, presence: true
	validates :message, presence: true
	validates :subject, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.all
	end
	def new
		@employee = Employee.new
	end
	def create
		@employee = Employee.new(employee_params)

		if @employee.save
			redirect_to employees_path, notice: "employee is created"
		else
			render :new
		end
	end
	def edit
		@employee = Employee.find(params[:id])
		
	end
	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
			redirect_to employees_path, notice: "employee status is changed"
		else
			render :edit
		end
	end
	def show
		@employee = Employee.find(params[:id])
	end
	def destroy
		@employee = Employee.find(params[:id])
		if @employee.destroy
			redirect_to employees_path, notice: "employee is delete"
		end
	end

	private
	def employee_params
		params.require(:employee).permit(:name, :contact, :address)
	end
end

app/controllers/maxx_controller.rb
class MaxxController < ApplicationController
	def new
		@webb = Webb.new
	end
	def create
		@webb = Webb.new(webb_params)
		if @webb.save
			@email = @webb.email
			@message = @webb.message
			@subject = @webb.subject
			PostmailerMailer.post_created(@message,@email,@subject).deliver_now
			redirect_to detail_path
		end
	end
	def show
		@webb = Webb.all
	end

	def connect
		@mail = "gulshanconnection@gmail.com"
		@email = Webb.last.email
		@subject = Webb.last.subject
		@message = Webb.last.message

	end


	private
    def webb_params
    	params.require(:webb).permit(:email, :message, :subject)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/employees/create.html.erb
<p> this is something </p>

app/views/employees/edit.html.erb
<div class="row col-lg-12">
    <div class="card mt5 mb-5">
		<div class="card-body">
			<h2 class="text-center">edit employee</h2>
		</div>
	</div>

	<%= form_with model: @employee do |form| %>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :name, class: "mb-2" %>
					<%= form.text_field :name, class: "form-control form-control-lg" %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :contact, class: "mb-2" %>
					<%= form.text_field :contact, class: "form-control form-control-lg" %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :address, class: "mb-2" %>
					<%= form.text_field :address, class: "form-control form-control-lg" %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 mt-4">
				<%= form.submit class: "btn btn-primary btn-lg" %>
				<%= link_to "back to employee", employees_path, class: "btn btn-outline-primary btn-lg" %>

			</div>
		</div>

	<% end %>
</div>

app/views/employees/index.html.erb
<div class="row col-lg-12">
	<%= flash[:notice] %>
    <div class="card mt5 mb-5 ">
		<div class="card-body">
			<h2 class="text-center">Listing Employees</h2>
		</div>
	</div>
	<%= link_to "create employee new", new_path, class: "btn btn-primary btn-lg mb-4"  %>
	<%= link_to "email", maxx_path, class: "btn btn-primary btn-lg mb-4"  %>
	
	<table class="table table-bordered">
		<tread>
			<tr>
				<th>name</th>
				<th>contact</th>
				<th>address</th>
				<th>Actions</th>
			</tr>
		</tread>
		<tbody>
			<% @employees.each do |employee| %>
				<tr>
					<td><%= employee.name %></td>
					<td><%= employee.contact %></td>
					<td><%= employee.address %></td>
					<td>
						<%= link_to "edit", edit_employee_path(employee), class: "btn btn-primary" %>
						<%= link_to "show", employee_path(employee), class: "btn btn-primary" %>
						<%= link_to "delete", employee_path(employee), class: "btn btn-danger", method: :delete, data: {confirm: "really want to "} %>
					</td>
				</tr> 
			<% end %>
		</tbody>
	</table>
</div>

app/views/employees/new.html.erb
<div class="row col-lg-12">
    <div class="card mt5 mb-5">
		<div class="card-body">
			<h2 class="text-center">Create Employee</h2>
		</div>
	</div>

	<%= form_with model: @employee do |form| %>
		<div class="row">
			<% if @employee.errors.any? %>
				<div class="col-lg-12">
					<p class="lead">please fix errors below</p>
					<% @employee.errors.full_messages.each do |message| %>
						<p class="text-danger"><%= message %></p>
					<% end %>
				</div>
			<% end %>
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :name, class: "mb-2" %>
					<%= form.text_field :name, class: "form-control form-control-lg" %>
					<% @employee.errors.full_messages_for(:name).each do |message| %>
						<P class="text-danger"><%= message %></P>
					<% end %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :contact, class: "mb-2" %>
					<%= form.text_field :contact, class: "form-control form-control-lg" %>
					<% @employee.errors.full_messages_for(:contact).each do |message| %>
						<P class="text-danger"><%= message %></P>
					<% end %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="form-group">
					<%= form.label :address, class: "mb-2" %>
					<%= form.text_field :address, class: "form-control form-control-lg" %>
					<% @employee.errors.full_messages_for(:address).each do |message| %>
						<P class="text-danger"><%= message %></P>
					<% end %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12 mt-4">
				<%= form.submit class: "btn btn-primary btn-lg" %>
				<%= link_to "back to employee", employees_path, class: "btn btn-outline-primary btn-lg" %>

			</div>
		</div>

	<% end %>
</div>

app/views/employees/show.html.erb
<div class="row col-lg-12">
    <div class="card mt5 mb-5 ">
		<div class="card-body">
			<h2 class="text-center">Employee's personal detail</h2>
			<div class="row">
				<p class="lead"><strong>Name:</strong> <%= @employee.name %></p>
				<p class="lead"><stong>contact:</stong> <%= @employee.contact %></p>
				<p class="lead"><strong>Address:</strong><%= @employee.address %></p>
			</div>
			<%= link_to "back to employee", employees_path, class: "btn btn-outline-primary btn-lg" %>
			<%= link_to "edit", edit_employee_path(@employee), class: "btn btn-outline-primary btn-lg" %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Play</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


  </body>
</html>

app/views/master/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "book", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/master/_link.html.erb
<%= link_to "contact number" ,number_path, target: '_blank' %>

<%= link_to "address" ,address_path, target: '_blank' %>

app/views/maxx/connect.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Email Template</title>
	<style type="text/css">
		body {
			margin: 0;
			padding: 0;
			background-color: #f5f5f5;
			font-family: Arial, Helvetica, sans-serif;
			font-size: 16px;
			line-height: 1.5;
			color: #333333;
		}

		.container {
			max-width: 600px;
			margin: 0 auto;
			padding: 20px;
			background-color: #ffffff;
		}

		h1 {
			margin-top: 0;
			font-size: 24px;
			font-weight: bold;
			color: #333333;
		}

		p {
			margin-bottom: 20px;
		}

		.bold {
			font-weight: bold;
		}
	</style>
</head>
<body>
	<div class="container">
		<p class="bold">From:</p>
		<p><%= @mail %></p>
		<p class="bold">To:</p>
		<p><%= @email %></p>
		<p class="bold">Subject:</p>
		<p><%= @subject %></p>
		<p class="bold">Message:</p>
		<p><%= @message %></p>
		<h1> <%= link_to "back to mail", maxx_path %> </h1>
	</div>
</body>
</html>

app/views/maxx/new.html.erb
<h1>Login</h1>

<%= form_for @webb, url: maxx_path do |f| %>
  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% end %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_field :message, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, class: 'form-control', required: true %>
  </div>


  <%= f.submit 'mail', class: 'btn btn-primary' %>
  <h1> <%= link_to "create employee", employees_path, class: 'btn btn-primary' %> </h1>
<% end %>

app/views/maxx/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="card mt-5 mb-5">
        <div class="card-body">
          <h2 class="text-center">Mail</h2>
        </div>
      </div>
      
      <%= link_to "Create Mail", maxx_path, class: "btn btn-primary btn-lg mb-4" %>
      
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Email</th>
            <th>Message</th>
            <th>Subject</th>
          </tr>
        </thead>
        <tbody>
          <% @webb.each do |webb| %>
            <tr>
              <td><%= webb.email %></td>
              <td><%= webb.message %></td>
              <td><%= webb.subject %></td>
            </tr> 
          <% end %>
        </tbody>
      </table>
      
    </div>
  </div>
</div>